CREATE TABLE Contacts(
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Firstname VARCHAR(50) NOT NULL,
    Lastname VARCHAR(100) NOT NULL,
    `Address` VARCHAR(200) NOT NULL,
    Zipcode VARCHAR(10) NOT NULL,
    City VARCHAR(100) NOT NULL,
    Country VARCHAR(100) NOT NULL,
    Email VARCHAR(128) NULL
)